services:
  landing:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VITE_APPLE_CLIENT_ID: ${VITE_APPLE_CLIENT_ID}
        VITE_APPLE_REDIRECT_URI: ${VITE_APPLE_REDIRECT_URI}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    container_name: landing
    restart: always
    ports:
      - "3001:3000"